apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: roboshop
    component: mysql
    tier: backend
    environment: dev
  annontations:
    description: "This pod is created to demonstrate pod annotation"
    jenks: "https://jenkins.com/build/job/roboshop-catalogue/3"
spec:
  containers:
  - name: nginx
    image: nginx
