apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    purpose: service-demo
spec:
  selector:
    purpose: sevice-demo
    project: roboshop
    enviornment: dev
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    purpose: service-demo
    project: roboshop
    enviornment: dev
spec:
  containers:
  - name: nginx
    image: nginx